services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - pacs
    volumes:
      - ${POSTGRES_DATA_MNT}:${PGDATA}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}

  pacs:
    container_name: orthanc
    image: jodogne/orthanc-plugins
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      # configuration file
      - ${ORTHANC_CONFIG}:/etc/orthanc/orthanc.json:ro
      # storage volume for raw dicoms
      - ${ORTHANC_DB_MNT}:/var/lib/orthanc/db/
    environment:
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"
      VOLVIEW_PLUGIN_ENABLED: "true"
    restart: always
    networks:
      - pacs
    depends_on:
      - postgres
      
  ohif:
    container_name: ohif
    image: ohif/viewer
    ports:
      - 3000:80
    environment:
      - APP_CONFIG:/usr/share/nginx/html/app-config.js
    volumes:
      - ${NGINX_DEFAULT_CONF}:/etc/nginx/conf.d/default.conf:ro
      - ${VIEWER_CONFIG}:/usr/share/nginx/html/app-config.js:ro
      - ./logo.png:/usr/share/nginx/html/logo.png:ro
    restart: always      
    networks:
      - pacs

networks:
  pacs:
    external: true
