version: "3"
services:
  orthanc-db:
    image: postgres
    container_name: orthanc-db
    environment:
      POSTGRES_PASSWORD: "pg-password"
    volumes:
      - ./pg_sql:/var/lib/postgresql/data

  pacs:
    container_name: orthanc
    image: jodogne/orthanc-plugins
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc_db:/var/lib/orthanc/db/
    environment:
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"
      VOLVIEW_PLUGIN_ENABLED: "true"
    restart: always
    networks:
      - pacs
    depends_on:
      - orthanc-db
      
  ohif_viewer:
    container_name: ohif
    image: ohif/viewer
    ports:
      - 3000:80
    environment:
      - APP_CONFIG:/usr/share/nginx/html/app-config.js
    volumes:
      - ./nginx_ohif.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ohif.js:/usr/share/nginx/html/app-config.js:ro
      - ./logo.png:/usr/share/nginx/html/logo.png:ro
    restart: always
    networks:
      - pacs

networks:
  pacs:
    external: true
